name: deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

    deploy:
        name: Deploy newly build container
        runs-on: ubuntu-latest
        env:
          IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT }}/webapi
          INS_TEMPLATES: webapi-templates-${{ github.sha }}
          REGION: us-central1
          NETWORK: default
          SUBNET: default
        steps:

        - name: Login
          uses: google-github-actions/setup-gcloud@v0
          with:
            project_id: ${{ secrets.GCP_PROJECT }}
            service_account_email: ${{ secrets.GCP_EMAIL }}
            service_account_key: ${{ secrets.GCP_SA_KEY }}

        - name: Configure Docker
          run: gcloud auth configure-docker --quiet

        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Build Docker image
          run: |
            docker build \
            --build-arg dbHost=${{ secrets.DB_HOST }} \
            --build-arg dbPass=${{ secrets.DB_PASSWORD }} \
            --build-arg firestoreCred=${{ secrets.FIRESTORE_SA_KEY }} \
            . -t $IMAGE_NAME

        - name: Push Docker image
          run: docker push $IMAGE_NAME

        - name: create instance template
          run: |
            gcloud compute instance-templates create-with-container ${{ env.INS_TEMPLATES }} \
              --container-image=${{ env.IMAGE_NAME }}:latest \
              --tags=http-server --machine-type=e2-micro --boot-disk-size=40 \
              --network=${{ env.NETWORK }} --subnet=${{ env.SUBNET }} --no-address --region=${{ env.REGION }}
        
        - name: create new MIG
          run: |
            gcloud compute instance-groups managed rolling-action start-update webapi-mig \
              --version=template=${{ env.INS_TEMPLATES }} \
              --type=proactive --region=${{ env.REGION}} 
